version: '3.7'

services:
  db:
    image: postgres
    container_name: "database"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - my_internal_network
    volumes:
      - postgres_volume:/var/lib/postgres/data
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - my_internal_network

volumes:
  postgres_volume:
networks:
  my_internal_network:
    driver: bridge
